export const cities = ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Peshawar"];

export const categories = [
  { name: "Nurses", icon: "heart", count: "2,451" },
  { name: "Maids", icon: "home", count: "1,892" },
  { name: "Drivers", icon: "car", count: "3,210" },
  { name: "Teachers", icon: "graduation", count: "2,870" },
  { name: "Electricians", icon: "plug", count: "1,342" },
  { name: "Plumbers", icon: "wrench", count: "1,118" },
  { name: "Security Guards", icon: "shield", count: "968" },
  { name: "Beauticians", icon: "scissors", count: "1,537" },
  { name: "Handwriting Teachers", icon: "paintbrush", count: "412" },
  { name: "Tutors", icon: "graduation", count: "2,690" },
  { name: "Home Tutors", icon: "home", count: "1,884" },
  { name: "Quran Teachers", icon: "graduation", count: "1,260" },
  { name: "Cooks", icon: "chef", count: "1,438" },
  { name: "Office Boys", icon: "briefcase", count: "721" },
  { name: "Peons", icon: "userCheck", count: "604" },
  { name: "Gardeners", icon: "leaf", count: "539" },
  { name: "Carpenters", icon: "hammer", count: "826" },
  { name: "AC Technicians", icon: "drill", count: "1,176" },
  { name: "Mechanics", icon: "wrench", count: "934" },
  { name: "Painters", icon: "palette", count: "745" },
  { name: "Welders", icon: "drill", count: "383" },
  { name: "Tailors", icon: "scissors", count: "1,024" },
  { name: "Babysitters", icon: "users", count: "692" },
  { name: "Caregivers", icon: "stethoscope", count: "864" },
  { name: "Physiotherapists", icon: "heart", count: "298" },
  { name: "Lab Technicians", icon: "stethoscope", count: "344" },
  { name: "Artists", icon: "palette", count: "571" },
  { name: "Graphic Designers", icon: "pencil", count: "783" },
  { name: "Photographers", icon: "image", count: "649" },
  { name: "Event Staff", icon: "contact", count: "902" },
  { name: "Delivery Riders", icon: "bike", count: "1,715" },
];

export const recentProfessionals = [
  {
    id: "maryam-safdar",
    name: "Maryam Safdar",
    role: "Beautician",
    city: "Rawalpindi",
    area: "Saddar",
    rating: "4.9",
    ratingCount: "184 reviews",
    experience: "5 years experience",
    rate: "From Rs. 3,500/session",
    bio: "Home and event beautician for makeup, hair styling, and party looks.",
    responseTime: "Replies in 12 min",
    image: "/avatars/pro-1.svg",
  },
  {
    id: "bilal-ahmed",
    name: "Bilal Ahmed",
    role: "Driver",
    city: "Karachi",
    area: "Gulshan-e-Iqbal",
    rating: "4.8",
    ratingCount: "231 reviews",
    experience: "8 years experience",
    rate: "From Rs. 2,000/day",
    bio: "Experienced city and intercity driver with clean vehicle handling record.",
    responseTime: "Replies in 8 min",
    image: "/avatars/pro-2.svg",
  },
  {
    id: "hafsa-rehman",
    name: "Hafsa Rehman",
    role: "Quran Teacher",
    city: "Lahore",
    area: "Johar Town",
    rating: "5.0",
    ratingCount: "96 reviews",
    experience: "6 years experience",
    rate: "From Rs. 8,000/month",
    bio: "Quran teacher for children and women with tajweed and basic Islamic studies.",
    responseTime: "Replies in 20 min",
    image: "/avatars/pro-3.svg",
  },
  {
    id: "ayesha-noor",
    name: "Ayesha Noor",
    role: "Home Nurse",
    city: "Islamabad",
    area: "G-10",
    rating: "4.9",
    ratingCount: "143 reviews",
    experience: "7 years experience",
    rate: "From Rs. 2,500/day",
    bio: "Home nurse for elderly care, medication support, and post-operative care.",
    responseTime: "Replies in 15 min",
    image: "/avatars/pro-4.svg",
  },
  {
    id: "rashid-khan",
    name: "Rashid Khan",
    role: "Electrician",
    city: "Peshawar",
    area: "University Road",
    rating: "4.7",
    ratingCount: "118 reviews",
    experience: "10 years experience",
    rate: "From Rs. 1,200/visit",
    bio: "Electrician for wiring, switchboards, fans, lights, and emergency repairs.",
    responseTime: "Replies in 10 min",
    image: "/avatars/pro-5.svg",
  },
  {
    id: "sana-tariq",
    name: "Sana Tariq",
    role: "Home Tutor",
    city: "Faisalabad",
    area: "Madina Town",
    rating: "4.9",
    ratingCount: "205 reviews",
    experience: "4 years experience",
    rate: "From Rs. 12,000/month",
    bio: "Home tutor for primary and middle school students, focused on Maths and English.",
    responseTime: "Replies in 18 min",
    image: "/avatars/pro-6.svg",
  },
];
